runtime: python
env: flex

env_variables:
  TOKEN: 1234abcd
  CONNECTION_NAME: ai-dj-36:us-west2:bigdata
  DB_USER: postgres
  DB_PASSWORD: HnusABOqiqMGfL00
  DB_NAME: postgres

beta_settings:
  cloud_sql_instances: ai-dj-36:us-west2:bigdata


# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn -b :$PORT -k flask_sockets.worker main:app

runtime_config:
  python_version: 3
