runtime: python
env: flex

# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn -b :$PORT -k flask_sockets.worker main:app

runtime_config:
  python_version: 3

env_variables:
  TOKEN: 1234abcd
